import React from 'react';

const TermsList = ({ lines }: { lines: string[] }) => (
    <ul className='list-disc list-inside'>
        {lines.map((line, index) => (
            <li key={index}>{line}</li>
        ))}
    </ul>
);

const TermsSection = ({ title, description, lines }: { title: string; description?: string; lines?: string[] }) => (
    <div className='mb-4'>
        <h2 className='text-lg font-bold mb-2'>{title}</h2>
        {description && <h3 className='mb-2'>{description}</h3>}
        {lines && <TermsList lines={lines} />}
    </div>
);

const TermsAndConditions: React.FC = () => (
    <>
        <div className='space-y-4 text-sm sm:text-base leading-relaxed'>
            <h1 className='text-2xl font-bold mb-3'>Terms & Conditions</h1>
            <h2>Effective Date: 1 December 2024 </h2>

            <TermsSection
                title='1. General Information'
                description='Welcome to CV Builder ("the Service"). By using our platform, you agree to these Terms and Conditions. If you do not agree, please refrain from using the Service.'
            />

            <TermsSection
                title='2. AI-Generated Content Disclaimer'
                description='The CVs and related content generated by our Service are created using artificial intelligence. While we aim for accuracy and usefulness, the following applies:'
                lines={[
                    'The generated content may contain errors or inaccuracies.',
                    'Users must carefully review and edit the CVs before use.',
                    'The Service does not guarantee employment, interviews, or specific outcomes based on the generated CVs.'
                ]}
            />

            <TermsSection
                title='3. User Responsibility'
                lines={[
                    'Users are responsible for the accuracy, legality, and truthfulness of the information they input into the Service.',
                    'The Service does not fact-check or verify the input provided by users.'
                ]}
            />

            <TermsSection
                title='4. No Liability'
                lines={[
                    '[Your App Name] is not liable for any errors, omissions, or inaccuracies in the generated CVs.',
                    'We are not responsible for any decisions, outcomes, or consequences arising from the use of the generated CVs.'
                ]}
            />

            <TermsSection
                title='5. Intellectual Property'
                lines={[
                    'Users retain ownership of the CVs generated using their input.',
                    '[Your App Name] retains the right to use anonymized and aggregated data for improving the Service.'
                ]}
            />

            <TermsSection
                title='6. Data Privacy'
                lines={[
                    'Your data is processed in accordance with our Privacy Policy.',
                    'Personal information will not be shared with third parties without explicit consent, except as required by law.'
                ]}
            />

            <TermsSection
                title='7. Service Limitations'
                lines={[
                    'The Service is provided "as-is" and "as-available" without any warranty of performance.',
                    'We reserve the right to modify, suspend, or discontinue the Service at any time without notice.'
                ]}
            />

            <TermsSection
                title='8. Acceptable Use'
                lines={[
                    'Users must not use the Service for unlawful purposes or in violation of these Terms.',
                    'Misuse of the platform may result in account suspension or termination.'
                ]}
            />

            <TermsSection
                title='9. Updates to Terms'
                description='We may update these Terms at any time. Continued use of the Service after such updates constitutes acceptance of the new Terms.'
            />

            <TermsSection
                title='10. Governing Law'
                lines={['These Terms are governed by the laws of [Your Country/Region].']}
            />

            <TermsSection
                title='11. Contact Information'
                description='For questions or concerns about these Terms, please contact us at [Your Contact Email].'
            />
        </div>
    </>
);

export default TermsAndConditions;
